---
- name: Install Zsh and Git
  ansible.builtin.apt:
    name: ["zsh", "git"]
    state: present

- name: Install Oh My Zsh for users with Zsh shell
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh-install.sh
    mode: 0755

- name: Run Zsh installer
  ansible.builtin.command: /tmp/oh-my-zsh-install.sh --unattended
  args:
    creates: "/home/{{ item.name }}/.oh-my-zsh"
  loop: "{{ users }}"
  when: item.shell == "/bin/zsh"
  become: true
  become_user: "{{ item.name }}"

- name: Set Zsh as default shell for Zsh users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/zsh
  loop: "{{ users }}"
  when: item.shell == "/bin/zsh"